// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testCropHints(t *testing.T) {
	t.Parallel()

	query := CropHints(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testCropHintsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = cropHint.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCropHintsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = CropHints(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCropHintsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CropHintSlice{cropHint}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testCropHintsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := CropHintExists(tx, cropHint.CropID)
	if err != nil {
		t.Errorf("Unable to check if CropHint exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CropHintExistsG to return true, but got false.")
	}
}
func testCropHintsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	cropHintFound, err := FindCropHint(tx, cropHint.CropID)
	if err != nil {
		t.Error(err)
	}

	if cropHintFound == nil {
		t.Error("want a record, got nil")
	}
}
func testCropHintsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = CropHints(tx).Bind(cropHint); err != nil {
		t.Error(err)
	}
}

func testCropHintsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := CropHints(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCropHintsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHintOne := &CropHint{}
	cropHintTwo := &CropHint{}
	if err = randomize.Struct(seed, cropHintOne, cropHintDBTypes, false, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}
	if err = randomize.Struct(seed, cropHintTwo, cropHintDBTypes, false, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHintOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = cropHintTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := CropHints(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCropHintsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	cropHintOne := &CropHint{}
	cropHintTwo := &CropHint{}
	if err = randomize.Struct(seed, cropHintOne, cropHintDBTypes, false, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}
	if err = randomize.Struct(seed, cropHintTwo, cropHintDBTypes, false, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHintOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = cropHintTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func cropHintBeforeInsertHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintAfterInsertHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintAfterSelectHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintBeforeUpdateHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintAfterUpdateHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintBeforeDeleteHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintAfterDeleteHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintBeforeUpsertHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func cropHintAfterUpsertHook(e boil.Executor, o *CropHint) error {
	*o = CropHint{}
	return nil
}

func testCropHintsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &CropHint{}
	o := &CropHint{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, cropHintDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CropHint object: %s", err)
	}

	AddCropHintHook(boil.BeforeInsertHook, cropHintBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	cropHintBeforeInsertHooks = []CropHintHook{}

	AddCropHintHook(boil.AfterInsertHook, cropHintAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	cropHintAfterInsertHooks = []CropHintHook{}

	AddCropHintHook(boil.AfterSelectHook, cropHintAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	cropHintAfterSelectHooks = []CropHintHook{}

	AddCropHintHook(boil.BeforeUpdateHook, cropHintBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	cropHintBeforeUpdateHooks = []CropHintHook{}

	AddCropHintHook(boil.AfterUpdateHook, cropHintAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	cropHintAfterUpdateHooks = []CropHintHook{}

	AddCropHintHook(boil.BeforeDeleteHook, cropHintBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	cropHintBeforeDeleteHooks = []CropHintHook{}

	AddCropHintHook(boil.AfterDeleteHook, cropHintAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	cropHintAfterDeleteHooks = []CropHintHook{}

	AddCropHintHook(boil.BeforeUpsertHook, cropHintBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	cropHintBeforeUpsertHooks = []CropHintHook{}

	AddCropHintHook(boil.AfterUpsertHook, cropHintAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	cropHintAfterUpsertHooks = []CropHintHook{}
}
func testCropHintsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCropHintsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx, cropHintColumns...); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCropHintToOnePageUsingPage(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local CropHint
	var foreign Page

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pageDBTypes, true, pageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Page struct: %s", err)
	}

	local.PageID.Valid = true

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.PageID.String = foreign.PageID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.Page(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.PageID != foreign.PageID {
		t.Errorf("want: %v, got %v", foreign.PageID, check.PageID)
	}

	slice := CropHintSlice{&local}
	if err = local.L.LoadPage(tx, false, &slice); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Page = nil
	if err = local.L.LoadPage(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testCropHintToOneSetOpPageUsingPage(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a CropHint
	var b, c Page

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cropHintDBTypes, false, strmangle.SetComplement(cropHintPrimaryKeyColumns, cropHintColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Page{&b, &c} {
		err = a.SetPage(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Page != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CropHints[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PageID.String != x.PageID {
			t.Error("foreign key was wrong value", a.PageID.String)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PageID.String))
		reflect.Indirect(reflect.ValueOf(&a.PageID.String)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PageID.String != x.PageID {
			t.Error("foreign key was wrong value", a.PageID.String, x.PageID)
		}
	}
}

func testCropHintToOneRemoveOpPageUsingPage(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a CropHint
	var b Page

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cropHintDBTypes, false, strmangle.SetComplement(cropHintPrimaryKeyColumns, cropHintColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	if err = a.SetPage(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemovePage(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Page(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Page != nil {
		t.Error("R struct entry should be nil")
	}

	if a.PageID.Valid {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.CropHints) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testCropHintsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = cropHint.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testCropHintsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CropHintSlice{cropHint}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testCropHintsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := CropHints(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	cropHintDBTypes = map[string]string{`Confidence`: `character`, `CropID`: `uuid`, `ImportanceFraction`: `double precision`, `PageID`: `uuid`, `Xcomax`: `double precision`, `Xcomin`: `double precision`, `Ycomax`: `double precision`, `Ycomin`: `double precision`}
	_               = bytes.MinRead
)

func testCropHintsUpdate(t *testing.T) {
	t.Parallel()

	if len(cropHintColumns) == len(cropHintPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	if err = cropHint.Update(tx); err != nil {
		t.Error(err)
	}
}

func testCropHintsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(cropHintColumns) == len(cropHintPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	cropHint := &CropHint{}
	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, cropHint, cropHintDBTypes, true, cropHintPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(cropHintColumns, cropHintPrimaryKeyColumns) {
		fields = cropHintColumns
	} else {
		fields = strmangle.SetComplement(
			cropHintColumns,
			cropHintPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(cropHint))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := CropHintSlice{cropHint}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testCropHintsUpsert(t *testing.T) {
	t.Parallel()

	if len(cropHintColumns) == len(cropHintPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	cropHint := CropHint{}
	if err = randomize.Struct(seed, &cropHint, cropHintDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = cropHint.Upsert(tx, false, nil, nil); err != nil {
		t.Errorf("Unable to upsert CropHint: %s", err)
	}

	count, err := CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &cropHint, cropHintDBTypes, false, cropHintPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CropHint struct: %s", err)
	}

	if err = cropHint.Upsert(tx, true, nil, nil); err != nil {
		t.Errorf("Unable to upsert CropHint: %s", err)
	}

	count, err = CropHints(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
