// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v5"
)

// LabelAnnotation is an object representing the database table.
type LabelAnnotation struct {
	LabelID     string      `boil:"label_id" json:"label_id" toml:"label_id" yaml:"label_id"`
	PageID      null.String `boil:"page_id" json:"page_id,omitempty" toml:"page_id" yaml:"page_id,omitempty"`
	Description string      `boil:"description" json:"description" toml:"description" yaml:"description"`
	Score       float64     `boil:"score" json:"score" toml:"score" yaml:"score"`

	R *labelAnnotationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L labelAnnotationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// labelAnnotationR is where relationships are stored.
type labelAnnotationR struct {
	Page *Page
}

// labelAnnotationL is where Load methods for each relationship are stored.
type labelAnnotationL struct{}

var (
	labelAnnotationColumns               = []string{"label_id", "page_id", "description", "score"}
	labelAnnotationColumnsWithoutDefault = []string{"page_id", "description", "score"}
	labelAnnotationColumnsWithDefault    = []string{"label_id"}
	labelAnnotationPrimaryKeyColumns     = []string{"label_id"}
)

type (
	// LabelAnnotationSlice is an alias for a slice of pointers to LabelAnnotation.
	// This should generally be used opposed to []LabelAnnotation.
	LabelAnnotationSlice []*LabelAnnotation
	// LabelAnnotationHook is the signature for custom LabelAnnotation hook methods
	LabelAnnotationHook func(boil.Executor, *LabelAnnotation) error

	labelAnnotationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	labelAnnotationType                 = reflect.TypeOf(&LabelAnnotation{})
	labelAnnotationMapping              = queries.MakeStructMapping(labelAnnotationType)
	labelAnnotationPrimaryKeyMapping, _ = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, labelAnnotationPrimaryKeyColumns)
	labelAnnotationInsertCacheMut       sync.RWMutex
	labelAnnotationInsertCache          = make(map[string]insertCache)
	labelAnnotationUpdateCacheMut       sync.RWMutex
	labelAnnotationUpdateCache          = make(map[string]updateCache)
	labelAnnotationUpsertCacheMut       sync.RWMutex
	labelAnnotationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var labelAnnotationBeforeInsertHooks []LabelAnnotationHook
var labelAnnotationBeforeUpdateHooks []LabelAnnotationHook
var labelAnnotationBeforeDeleteHooks []LabelAnnotationHook
var labelAnnotationBeforeUpsertHooks []LabelAnnotationHook

var labelAnnotationAfterInsertHooks []LabelAnnotationHook
var labelAnnotationAfterSelectHooks []LabelAnnotationHook
var labelAnnotationAfterUpdateHooks []LabelAnnotationHook
var labelAnnotationAfterDeleteHooks []LabelAnnotationHook
var labelAnnotationAfterUpsertHooks []LabelAnnotationHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *LabelAnnotation) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *LabelAnnotation) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *LabelAnnotation) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *LabelAnnotation) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *LabelAnnotation) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *LabelAnnotation) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *LabelAnnotation) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *LabelAnnotation) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *LabelAnnotation) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range labelAnnotationAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLabelAnnotationHook registers your hook function for all future operations.
func AddLabelAnnotationHook(hookPoint boil.HookPoint, labelAnnotationHook LabelAnnotationHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		labelAnnotationBeforeInsertHooks = append(labelAnnotationBeforeInsertHooks, labelAnnotationHook)
	case boil.BeforeUpdateHook:
		labelAnnotationBeforeUpdateHooks = append(labelAnnotationBeforeUpdateHooks, labelAnnotationHook)
	case boil.BeforeDeleteHook:
		labelAnnotationBeforeDeleteHooks = append(labelAnnotationBeforeDeleteHooks, labelAnnotationHook)
	case boil.BeforeUpsertHook:
		labelAnnotationBeforeUpsertHooks = append(labelAnnotationBeforeUpsertHooks, labelAnnotationHook)
	case boil.AfterInsertHook:
		labelAnnotationAfterInsertHooks = append(labelAnnotationAfterInsertHooks, labelAnnotationHook)
	case boil.AfterSelectHook:
		labelAnnotationAfterSelectHooks = append(labelAnnotationAfterSelectHooks, labelAnnotationHook)
	case boil.AfterUpdateHook:
		labelAnnotationAfterUpdateHooks = append(labelAnnotationAfterUpdateHooks, labelAnnotationHook)
	case boil.AfterDeleteHook:
		labelAnnotationAfterDeleteHooks = append(labelAnnotationAfterDeleteHooks, labelAnnotationHook)
	case boil.AfterUpsertHook:
		labelAnnotationAfterUpsertHooks = append(labelAnnotationAfterUpsertHooks, labelAnnotationHook)
	}
}

// OneP returns a single labelAnnotation record from the query, and panics on error.
func (q labelAnnotationQuery) OneP() *LabelAnnotation {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single labelAnnotation record from the query.
func (q labelAnnotationQuery) One() (*LabelAnnotation, error) {
	o := &LabelAnnotation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for label_annotation")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all LabelAnnotation records from the query, and panics on error.
func (q labelAnnotationQuery) AllP() LabelAnnotationSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all LabelAnnotation records from the query.
func (q labelAnnotationQuery) All() (LabelAnnotationSlice, error) {
	var o LabelAnnotationSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to LabelAnnotation slice")
	}

	if len(labelAnnotationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all LabelAnnotation records in the query, and panics on error.
func (q labelAnnotationQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all LabelAnnotation records in the query.
func (q labelAnnotationQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count label_annotation rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q labelAnnotationQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q labelAnnotationQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if label_annotation exists")
	}

	return count > 0, nil
}

// PageG pointed to by the foreign key.
func (o *LabelAnnotation) PageG(mods ...qm.QueryMod) pageQuery {
	return o.Page(boil.GetDB(), mods...)
}

// Page pointed to by the foreign key.
func (o *LabelAnnotation) Page(exec boil.Executor, mods ...qm.QueryMod) pageQuery {
	queryMods := []qm.QueryMod{
		qm.Where("page_id=?", o.PageID),
	}

	queryMods = append(queryMods, mods...)

	query := Pages(exec, queryMods...)
	queries.SetFrom(query.Query, "\"page\"")

	return query
}

// LoadPage allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (labelAnnotationL) LoadPage(e boil.Executor, singular bool, maybeLabelAnnotation interface{}) error {
	var slice []*LabelAnnotation
	var object *LabelAnnotation

	count := 1
	if singular {
		object = maybeLabelAnnotation.(*LabelAnnotation)
	} else {
		slice = *maybeLabelAnnotation.(*LabelAnnotationSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &labelAnnotationR{}
		}
		args[0] = object.PageID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &labelAnnotationR{}
			}
			args[i] = obj.PageID
		}
	}

	query := fmt.Sprintf(
		"select * from \"page\" where \"page_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Page")
	}
	defer results.Close()

	var resultSlice []*Page
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Page")
	}

	if len(labelAnnotationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Page = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PageID.String == foreign.PageID {
				local.R.Page = foreign
				break
			}
		}
	}

	return nil
}

// SetPageG of the label_annotation to the related item.
// Sets o.R.Page to related.
// Adds o to related.R.LabelAnnotations.
// Uses the global database handle.
func (o *LabelAnnotation) SetPageG(insert bool, related *Page) error {
	return o.SetPage(boil.GetDB(), insert, related)
}

// SetPageP of the label_annotation to the related item.
// Sets o.R.Page to related.
// Adds o to related.R.LabelAnnotations.
// Panics on error.
func (o *LabelAnnotation) SetPageP(exec boil.Executor, insert bool, related *Page) {
	if err := o.SetPage(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPageGP of the label_annotation to the related item.
// Sets o.R.Page to related.
// Adds o to related.R.LabelAnnotations.
// Uses the global database handle and panics on error.
func (o *LabelAnnotation) SetPageGP(insert bool, related *Page) {
	if err := o.SetPage(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPage of the label_annotation to the related item.
// Sets o.R.Page to related.
// Adds o to related.R.LabelAnnotations.
func (o *LabelAnnotation) SetPage(exec boil.Executor, insert bool, related *Page) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"label_annotation\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"page_id"}),
		strmangle.WhereClause("\"", "\"", 2, labelAnnotationPrimaryKeyColumns),
	)
	values := []interface{}{related.PageID, o.LabelID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PageID.String = related.PageID
	o.PageID.Valid = true

	if o.R == nil {
		o.R = &labelAnnotationR{
			Page: related,
		}
	} else {
		o.R.Page = related
	}

	if related.R == nil {
		related.R = &pageR{
			LabelAnnotations: LabelAnnotationSlice{o},
		}
	} else {
		related.R.LabelAnnotations = append(related.R.LabelAnnotations, o)
	}

	return nil
}

// RemovePageG relationship.
// Sets o.R.Page to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *LabelAnnotation) RemovePageG(related *Page) error {
	return o.RemovePage(boil.GetDB(), related)
}

// RemovePageP relationship.
// Sets o.R.Page to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *LabelAnnotation) RemovePageP(exec boil.Executor, related *Page) {
	if err := o.RemovePage(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePageGP relationship.
// Sets o.R.Page to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *LabelAnnotation) RemovePageGP(related *Page) {
	if err := o.RemovePage(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemovePage relationship.
// Sets o.R.Page to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *LabelAnnotation) RemovePage(exec boil.Executor, related *Page) error {
	var err error

	o.PageID.Valid = false
	if err = o.Update(exec, "page_id"); err != nil {
		o.PageID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Page = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.LabelAnnotations {
		if o.PageID.String != ri.PageID.String {
			continue
		}

		ln := len(related.R.LabelAnnotations)
		if ln > 1 && i < ln-1 {
			related.R.LabelAnnotations[i] = related.R.LabelAnnotations[ln-1]
		}
		related.R.LabelAnnotations = related.R.LabelAnnotations[:ln-1]
		break
	}
	return nil
}

// LabelAnnotationsG retrieves all records.
func LabelAnnotationsG(mods ...qm.QueryMod) labelAnnotationQuery {
	return LabelAnnotations(boil.GetDB(), mods...)
}

// LabelAnnotations retrieves all the records using an executor.
func LabelAnnotations(exec boil.Executor, mods ...qm.QueryMod) labelAnnotationQuery {
	mods = append(mods, qm.From("\"label_annotation\""))
	return labelAnnotationQuery{NewQuery(exec, mods...)}
}

// FindLabelAnnotationG retrieves a single record by ID.
func FindLabelAnnotationG(labelID string, selectCols ...string) (*LabelAnnotation, error) {
	return FindLabelAnnotation(boil.GetDB(), labelID, selectCols...)
}

// FindLabelAnnotationGP retrieves a single record by ID, and panics on error.
func FindLabelAnnotationGP(labelID string, selectCols ...string) *LabelAnnotation {
	retobj, err := FindLabelAnnotation(boil.GetDB(), labelID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindLabelAnnotation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLabelAnnotation(exec boil.Executor, labelID string, selectCols ...string) (*LabelAnnotation, error) {
	labelAnnotationObj := &LabelAnnotation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"label_annotation\" where \"label_id\"=$1", sel,
	)

	q := queries.Raw(exec, query, labelID)

	err := q.Bind(labelAnnotationObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from label_annotation")
	}

	return labelAnnotationObj, nil
}

// FindLabelAnnotationP retrieves a single record by ID with an executor, and panics on error.
func FindLabelAnnotationP(exec boil.Executor, labelID string, selectCols ...string) *LabelAnnotation {
	retobj, err := FindLabelAnnotation(exec, labelID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *LabelAnnotation) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *LabelAnnotation) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *LabelAnnotation) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *LabelAnnotation) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no label_annotation provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(labelAnnotationColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	labelAnnotationInsertCacheMut.RLock()
	cache, cached := labelAnnotationInsertCache[key]
	labelAnnotationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			labelAnnotationColumns,
			labelAnnotationColumnsWithDefault,
			labelAnnotationColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"label_annotation\" (\"%s\") VALUES (%s)", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"label_annotation\" DEFAULT VALUES"
		}

		if len(cache.retMapping) != 0 {
			cache.query += fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into label_annotation")
	}

	if !cached {
		labelAnnotationInsertCacheMut.Lock()
		labelAnnotationInsertCache[key] = cache
		labelAnnotationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single LabelAnnotation record. See Update for
// whitelist behavior description.
func (o *LabelAnnotation) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single LabelAnnotation record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *LabelAnnotation) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the LabelAnnotation, and panics on error.
// See Update for whitelist behavior description.
func (o *LabelAnnotation) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the LabelAnnotation.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *LabelAnnotation) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	labelAnnotationUpdateCacheMut.RLock()
	cache, cached := labelAnnotationUpdateCache[key]
	labelAnnotationUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(labelAnnotationColumns, labelAnnotationPrimaryKeyColumns, whitelist)
		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update label_annotation, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"label_annotation\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, labelAnnotationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, append(wl, labelAnnotationPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update label_annotation row")
	}

	if !cached {
		labelAnnotationUpdateCacheMut.Lock()
		labelAnnotationUpdateCache[key] = cache
		labelAnnotationUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q labelAnnotationQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q labelAnnotationQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for label_annotation")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o LabelAnnotationSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o LabelAnnotationSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o LabelAnnotationSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LabelAnnotationSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labelAnnotationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"UPDATE \"label_annotation\" SET %s WHERE (\"label_id\") IN (%s)",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(labelAnnotationPrimaryKeyColumns), len(colNames)+1, len(labelAnnotationPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in labelAnnotation slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *LabelAnnotation) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *LabelAnnotation) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *LabelAnnotation) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *LabelAnnotation) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no label_annotation provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(labelAnnotationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	labelAnnotationUpsertCacheMut.RLock()
	cache, cached := labelAnnotationUpsertCache[key]
	labelAnnotationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			labelAnnotationColumns,
			labelAnnotationColumnsWithDefault,
			labelAnnotationColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			labelAnnotationColumns,
			labelAnnotationPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert label_annotation, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(labelAnnotationPrimaryKeyColumns))
			copy(conflict, labelAnnotationPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"label_annotation\"", updateOnConflict, ret, update, conflict, whitelist)

		cache.valueMapping, err = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(labelAnnotationType, labelAnnotationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert label_annotation")
	}

	if !cached {
		labelAnnotationUpsertCacheMut.Lock()
		labelAnnotationUpsertCache[key] = cache
		labelAnnotationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single LabelAnnotation record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *LabelAnnotation) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single LabelAnnotation record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *LabelAnnotation) DeleteG() error {
	if o == nil {
		return errors.New("models: no LabelAnnotation provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single LabelAnnotation record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *LabelAnnotation) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single LabelAnnotation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LabelAnnotation) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no LabelAnnotation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), labelAnnotationPrimaryKeyMapping)
	sql := "DELETE FROM \"label_annotation\" WHERE \"label_id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from label_annotation")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q labelAnnotationQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q labelAnnotationQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no labelAnnotationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from label_annotation")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o LabelAnnotationSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o LabelAnnotationSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no LabelAnnotation slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o LabelAnnotationSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LabelAnnotationSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no LabelAnnotation slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(labelAnnotationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labelAnnotationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"DELETE FROM \"label_annotation\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, labelAnnotationPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(labelAnnotationPrimaryKeyColumns), 1, len(labelAnnotationPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from labelAnnotation slice")
	}

	if len(labelAnnotationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *LabelAnnotation) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *LabelAnnotation) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *LabelAnnotation) ReloadG() error {
	if o == nil {
		return errors.New("models: no LabelAnnotation provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LabelAnnotation) Reload(exec boil.Executor) error {
	ret, err := FindLabelAnnotation(exec, o.LabelID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *LabelAnnotationSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *LabelAnnotationSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LabelAnnotationSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty LabelAnnotationSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LabelAnnotationSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	labelAnnotations := LabelAnnotationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), labelAnnotationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"SELECT \"label_annotation\".* FROM \"label_annotation\" WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, labelAnnotationPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(labelAnnotationPrimaryKeyColumns), 1, len(labelAnnotationPrimaryKeyColumns)),
	)

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&labelAnnotations)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LabelAnnotationSlice")
	}

	*o = labelAnnotations

	return nil
}

// LabelAnnotationExists checks if the LabelAnnotation row exists.
func LabelAnnotationExists(exec boil.Executor, labelID string) (bool, error) {
	var exists bool

	sql := "select exists(select 1 from \"label_annotation\" where \"label_id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, labelID)
	}

	row := exec.QueryRow(sql, labelID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if label_annotation exists")
	}

	return exists, nil
}

// LabelAnnotationExistsG checks if the LabelAnnotation row exists.
func LabelAnnotationExistsG(labelID string) (bool, error) {
	return LabelAnnotationExists(boil.GetDB(), labelID)
}

// LabelAnnotationExistsGP checks if the LabelAnnotation row exists. Panics on error.
func LabelAnnotationExistsGP(labelID string) bool {
	e, err := LabelAnnotationExists(boil.GetDB(), labelID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// LabelAnnotationExistsP checks if the LabelAnnotation row exists. Panics on error.
func LabelAnnotationExistsP(exec boil.Executor, labelID string) bool {
	e, err := LabelAnnotationExists(exec, labelID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
