// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testTextAnnotations(t *testing.T) {
	t.Parallel()

	query := TextAnnotations(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testTextAnnotationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = textAnnotation.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTextAnnotationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = TextAnnotations(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTextAnnotationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := TextAnnotationSlice{textAnnotation}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testTextAnnotationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := TextAnnotationExists(tx, textAnnotation.TextID)
	if err != nil {
		t.Errorf("Unable to check if TextAnnotation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TextAnnotationExistsG to return true, but got false.")
	}
}
func testTextAnnotationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	textAnnotationFound, err := FindTextAnnotation(tx, textAnnotation.TextID)
	if err != nil {
		t.Error(err)
	}

	if textAnnotationFound == nil {
		t.Error("want a record, got nil")
	}
}
func testTextAnnotationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = TextAnnotations(tx).Bind(textAnnotation); err != nil {
		t.Error(err)
	}
}

func testTextAnnotationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := TextAnnotations(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTextAnnotationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotationOne := &TextAnnotation{}
	textAnnotationTwo := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotationOne, textAnnotationDBTypes, false, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}
	if err = randomize.Struct(seed, textAnnotationTwo, textAnnotationDBTypes, false, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotationOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = textAnnotationTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := TextAnnotations(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTextAnnotationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	textAnnotationOne := &TextAnnotation{}
	textAnnotationTwo := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotationOne, textAnnotationDBTypes, false, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}
	if err = randomize.Struct(seed, textAnnotationTwo, textAnnotationDBTypes, false, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotationOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = textAnnotationTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func textAnnotationBeforeInsertHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationAfterInsertHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationAfterSelectHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationBeforeUpdateHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationAfterUpdateHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationBeforeDeleteHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationAfterDeleteHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationBeforeUpsertHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func textAnnotationAfterUpsertHook(e boil.Executor, o *TextAnnotation) error {
	*o = TextAnnotation{}
	return nil
}

func testTextAnnotationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &TextAnnotation{}
	o := &TextAnnotation{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, textAnnotationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TextAnnotation object: %s", err)
	}

	AddTextAnnotationHook(boil.BeforeInsertHook, textAnnotationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	textAnnotationBeforeInsertHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.AfterInsertHook, textAnnotationAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	textAnnotationAfterInsertHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.AfterSelectHook, textAnnotationAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	textAnnotationAfterSelectHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.BeforeUpdateHook, textAnnotationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	textAnnotationBeforeUpdateHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.AfterUpdateHook, textAnnotationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	textAnnotationAfterUpdateHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.BeforeDeleteHook, textAnnotationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	textAnnotationBeforeDeleteHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.AfterDeleteHook, textAnnotationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	textAnnotationAfterDeleteHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.BeforeUpsertHook, textAnnotationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	textAnnotationBeforeUpsertHooks = []TextAnnotationHook{}

	AddTextAnnotationHook(boil.AfterUpsertHook, textAnnotationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	textAnnotationAfterUpsertHooks = []TextAnnotationHook{}
}
func testTextAnnotationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTextAnnotationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx, textAnnotationColumns...); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTextAnnotationToOnePageUsingPage(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local TextAnnotation
	var foreign Page

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pageDBTypes, true, pageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Page struct: %s", err)
	}

	local.PageID.Valid = true

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.PageID.String = foreign.PageID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.Page(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.PageID != foreign.PageID {
		t.Errorf("want: %v, got %v", foreign.PageID, check.PageID)
	}

	slice := TextAnnotationSlice{&local}
	if err = local.L.LoadPage(tx, false, &slice); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Page = nil
	if err = local.L.LoadPage(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testTextAnnotationToOneSetOpPageUsingPage(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a TextAnnotation
	var b, c Page

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, textAnnotationDBTypes, false, strmangle.SetComplement(textAnnotationPrimaryKeyColumns, textAnnotationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Page{&b, &c} {
		err = a.SetPage(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Page != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TextAnnotations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PageID.String != x.PageID {
			t.Error("foreign key was wrong value", a.PageID.String)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PageID.String))
		reflect.Indirect(reflect.ValueOf(&a.PageID.String)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PageID.String != x.PageID {
			t.Error("foreign key was wrong value", a.PageID.String, x.PageID)
		}
	}
}

func testTextAnnotationToOneRemoveOpPageUsingPage(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a TextAnnotation
	var b Page

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, textAnnotationDBTypes, false, strmangle.SetComplement(textAnnotationPrimaryKeyColumns, textAnnotationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	if err = a.SetPage(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemovePage(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Page(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Page != nil {
		t.Error("R struct entry should be nil")
	}

	if a.PageID.Valid {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.TextAnnotations) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTextAnnotationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = textAnnotation.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testTextAnnotationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := TextAnnotationSlice{textAnnotation}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testTextAnnotationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := TextAnnotations(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	textAnnotationDBTypes = map[string]string{`Description`: `character`, `Locale`: `character`, `PageID`: `uuid`, `TextID`: `uuid`, `Xcomax`: `double precision`, `Xcomin`: `double precision`, `Ycomax`: `double precision`, `Ycomin`: `double precision`}
	_                     = bytes.MinRead
)

func testTextAnnotationsUpdate(t *testing.T) {
	t.Parallel()

	if len(textAnnotationColumns) == len(textAnnotationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	if err = textAnnotation.Update(tx); err != nil {
		t.Error(err)
	}
}

func testTextAnnotationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(textAnnotationColumns) == len(textAnnotationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	textAnnotation := &TextAnnotation{}
	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, textAnnotation, textAnnotationDBTypes, true, textAnnotationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(textAnnotationColumns, textAnnotationPrimaryKeyColumns) {
		fields = textAnnotationColumns
	} else {
		fields = strmangle.SetComplement(
			textAnnotationColumns,
			textAnnotationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(textAnnotation))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := TextAnnotationSlice{textAnnotation}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testTextAnnotationsUpsert(t *testing.T) {
	t.Parallel()

	if len(textAnnotationColumns) == len(textAnnotationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	textAnnotation := TextAnnotation{}
	if err = randomize.Struct(seed, &textAnnotation, textAnnotationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = textAnnotation.Upsert(tx, false, nil, nil); err != nil {
		t.Errorf("Unable to upsert TextAnnotation: %s", err)
	}

	count, err := TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &textAnnotation, textAnnotationDBTypes, false, textAnnotationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TextAnnotation struct: %s", err)
	}

	if err = textAnnotation.Upsert(tx, true, nil, nil); err != nil {
		t.Errorf("Unable to upsert TextAnnotation: %s", err)
	}

	count, err = TextAnnotations(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
